name: gtbook-dev
channels:
  - conda-forge
dependencies:
- jupyter
- pandas
- python-graphviz
- matplotlib
- pillow
- pytorch
- pip
- pip:
  - nbdev
  - fastcore>=1.3.27
  - gtsam>=4.2a9
  - plotly
  - requests
